config/routes.rb
CMS::Application.routes.draw do

  resources :compuerta_pre_desicions

  resources :compuerta_desicions

  resources :tarea_aprobacions

  resources :tarea_revisions

  resources :actividad_revisions

  devise_for :users

  resources :tarea_artefactos

  resources :estado_tareas

  resources :tarea_participantes

  resources :tarea_presedencia

  resources :tarea_recursos

  resources :tareas

  resources :tipo_organizacions

  resources :proyecto_artefactos

  resources :artefactos

  resources :proyecto_usuarios

  resources :proyecto_recursos

  resources :proyecto_organizacions

  resources :transicions

  resources :procesos

  resources :usuarios

  resources :actividad_rols

  resources :actividad_tipoartefactos

  resources :tipo_artefactos

  resources :ruta

  resources :eventos

  resources :my_js_trees

  resources :actividad_tiporecursos

  resources :compuertus

  resources :compuerta

  resources :actividads

  resources :plantillas

  resources :tipo_plantillas

  resources :recursos

  resources :tipo_recursos

  resources :organizacions

  resources :rols

  resources :proyectos

  resources :tipo_productos

  resources :archivo_proyectos

  resources :archivos

  resources :tipo_archivos

  resources :deposito_proyectos

  resources :depositos

  resources :tipo_depositos

  resources :assignments

  resources :workers

  resources :projects

  match '*all' => 'application#cors_preflight_check', :constraints => {:method => 'OPTIONS'}



  match '/local/:id/use' => 'local#use'
  match '/local/:id/upload' => 'local#upload'
  match '/mediabrowser' => 'mediabrowser#list', :as => :discolocal
  match '/mediabrowser' => 'mediabrowser#list', :as => :mediabrowser
  match '/mediabrowser/delete' => 'mediabrowser#delete', :as => :delete_file_mediabrowser
  match '/mediabrowser/dir/create'  => 'mediabrowser#create_dir',  :as => :create_dir_mediabrowser
  match '/mediabrowser/file/create'  => 'mediabrowser#create_file',  :as => :create_file_mediabrowser

  match '/indexUsuario' => 'index#indexUsuario', :as => 'indexUsuario'
  match '/graficas' => 'index#graficas', :as => 'graficas'


  match '/tipo_recursos/existe/nombre' => 'tipo_recursos#existe', :as => :validacion_existe
  match '/recursos/existe/nombre' => 'recursos#existe', :as => :validacion_existe
  match '/tipo_plantillas/existe/nombre' => 'tipo_plantillas#existe', :as => :validacion_existe
  match '/tipo_organizacions/existe/nombre' => 'tipo_organizacions#existe', :as => :validacion_existe
  match '/plantillas/existe/nombre' => 'plantillas#existe', :as => :validacion_existe
  match '/tipo_artefactos/existe/nombre' => 'tipo_artefactos#existe', :as => :validacion_existe
  match '/actividads/existe/:nombre/:plantilla' => 'plantillas#existe', :as => :validacion_existe
  match '/actividads_turnos' => 'actividads#turnos', :as => :turnos # agregar turnos
  match '/actividad_revisor' => 'tarea_revisions#revisor', :as => :revisor # asignar revisores
  match '/compuerta_options' => 'compuerta_desicions#options', :as => :options #opciones compuerta
  match '/proyectos/existe/nombre' => 'proyectos#existe', :as => :validacion_existe
  match '/actividad_tiporecursos/existe/nombre' => 'actividad_tiporecursos#existe', :as => :validacion_existe
  match '/actividad_tipoartefactos/existe/nombre' => 'actividad_tipoartefactos#existe', :as => :validacion_existe
  match '/usuarios/existe/login' => 'usuarios#existe', :as => :validacion_existe
  match '/usuarios/password_iguales/pasword' => 'usuarios#password_iguales', :as => :validacion_password_iguales
  match '/rols/existe/nombre' => 'rols#existe', :as => :validacion_existe
  match '/organizacions/existe/nombre' => 'organizacions#existe', :as => :validacion_existe
  match '/organizacions/existe/nit' => 'organizacions#existenit', :as => :validacion_existenit
  match 'organizacions/existe/representante' => 'organizacions#existerepresentante', :as => :validacion_existerepresentante
  match 'organizacions/unico/representante' => 'organizacions#unicorepresentante', :as => :validacion_unicorepresentante

  match '/depositos/existe/nombre' => 'depositos#existe', :as => :validacion_existe

  match '/proyectos/:id/configu' => 'proyectos#configu', :as => :configu
  match '/proyectos/:id/configuempr' => 'proyectos#configuempr', :as => :configuempr
  match '/proyectos/:id/configupart' => 'proyectos#configupart', :as => :configupart
  match '/proyectos/:id/overview' => 'proyectos#overview', :as => :overview
  match '/proyectos/:id/priorizar' => 'proyectos#priorizar', :as => :priorizar
  match '/proyectos/:id/actualizarPriorizacion' => 'proyectos#actualizarPriorizacion', :as => :actualizarPriorizacion
  match '/proyectos/:id/actualizarPrior' => 'proyectos#actualizarPrior', :as => :actualizarPrior

  match '/proyectos/:id/priorizarTareas/:idusuario' => 'proyectos#priorizarTareas', :as => :priorizarTareas
  match '/proyectos/:id/arbol' => 'proyectos#arbol', :as => :arbol

  match   '/trees', :to => 'my_js_trees#jstree'
  match   '/treedata', :to => 'my_js_trees#jstreedata'


  match '/actividads/:id/destroy' => 'actividads#destroy', :as => :destroy
  match '/compuertus/:id/destroy' => 'compuertus#destroy', :as => :destroy
  match '/eventos/:id/destroy' => 'eventos#destroy', :as => :destroy
  match '/ruta/:id/destroy' => 'ruta#destroy', :as => :destroy

  match '/actividads/:id/updateName' => 'actividads#updateName', :as => :update
  match '/compuertus/:id/updateName' => 'compuertus#updateName', :as => :update
  match '/eventos/:id/updateName' => 'eventos#updateName', :as => :update
  match '/ruta/:id/updateName' => 'ruta#updateName', :as => :update
  match '/my_js_trees/:id/updateParent' => 'my_js_trees#updateParent', :as => :update

  match '/tarea_participantes/:id/updateEstado' => 'tarea_participantes#updateEstado', :as => :updateEstado
  match '/tarea_participantes/:id/updateHoras' => 'tarea_participantes#updateHoras', :as => :updateHoras


  match '/procesos/clonar_plantilla/:id_plantilla/:id_proyecto' => 'procesos#clonar_plantilla', :as => :clonar_plantilla

  match '/procesos/getTipoPlantilla/all' => 'procesos#getTipoPlantilla', :as => :getTipoPlantilla
  match '/procesos/getdata/:tipo_plantilla' => 'procesos#getdata', :as => :getdata
  match '/proyecto_organizacions/get_tipo_organizacions/all' => 'proyecto_organizacions#get_tipo_organizacions', :as => :get_tipo_organizacions
  match '/proyecto_organizacions/get_organizacions/:tipo_organizacion_id' => 'proyecto_organizacions#get_organizacions', :as => :get_organizacions
  match '/proyectos/get_organizaciones/all' => 'proyectos#get_organizaciones', :as => :get_organizaciones
  match '/proyectos/get_usuarios_org/:organizacion_id' => 'proyectos#get_usuarios_org', :as => :get_usuarios_org
  match '/depositos/get_tipo_depositos/all' => 'depositos#get_tipo_depositos', :as => :get_tipo_depositos
  match '/proyectos/getTipoRecurso/:id' => 'proyectos#getTipoRecurso', :as => :getTipoRecurso
  match '/proyectos/getdata/:id/:tipo_recurso' => 'proyectos#getdata', :as => :getdata

  match '/proyectos/listar_procesos/:id/:proy_id' => 'proyectos#listar_procesos', :as => :listar_procesos

  match '/procesos/:id_proceso/Reportes' => 'procesos#Reportes', :as => :Reportes, :action => 'Reportes'


  match "/procesos/:id_proceso/icons/:id", :to => redirect("/assets/%{id}.png")
  match "/procesos/:id_proceso/css/:id", :to => redirect("/assets/%{id}.css")
  match "/procesos/:id_proceso/scripts/:id", :to => redirect("/assets/%{id}.js")


  match '/procesos/:id_proceso/Reportes' => 'procesos#Reportes', :as => :Reportes
  match '/procesos/:id_proceso/Overview' => 'procesos#Overview', :as => :Overview
  match '/procesos/:id_proceso/Status' => 'procesos#Status', :as => :Status
  match '/procesos/:id_proceso/ResourceGraph' => 'procesos#ResourceGraph', :as => :ResourceGraph
  match '/procesos/:id_proceso/resourcesM' => 'procesos#resourcesM', :as => :resourcesM
  match '/procesos/:id_proceso/Work package 1' => 'procesos#Workpackage1', :as => :Workpackage1
  match '/procesos/:id_proceso/Work package 2' => 'procesos#Workpackage2', :as => :Workpackage2
  match '/procesos/:id_proceso/ContactList' => 'procesos#ContactList', :as => :ContactList
  match '/procesos/:id_proceso/Deliveries' => 'procesos#Deliveries', :as => :Deliveries
  match '/procesos/:id_proceso/Development' => 'procesos#Development', :as => :Development
  match '/procesos/:id_proceso/BurndownChart' => 'procesos#BurndownChart', :as => :BurndownChart
  match '/procesos/:id_proceso/xpdl' => 'procesos#GenerateXPDL', :as => :GenerateXPDL



  match '/procesos/:id_proceso/icons/:pag', :to => redirect('/assets/'||:pag)
  match '/procesos/:id_proceso/css/:pag', :to => redirect('/assets/'||:pag)
  match '/procesos/:id_proceso/scripts/:pag', :to => redirect('assets/'||:pag)

  match '/procesos/:id_proceso/crear_programa' => 'procesos#crear_programa', :as => :crear_programa
  match '/procesos/:id_proceso/aprobaciones' => 'procesos#aprobaciones', :as => :aprobaciones
  match '/tareas/:id_tarea/asignar_responsable' => 'tareas#asignar_responsable', :as => :asignar_responsable
  match '/tareas/:id_tarea/actualizar_tarea' => 'tareas#actualizar_tarea', :as => :actualizar_tarea
  match '/tareas/:id_tarea/get_json_data' => 'tareas#get_json_data', :as => :get_json_data

  match '/artefactos/:dummy/search_assets' => 'artefactos#search_assets', :as => :search_assets
  match '/basecamp/:id/get_proyectos' => 'basecamp#get_proyectos', :as => :get_proyectos
  match '/deposito_proyectos/:id/new' => 'deposito_proyectos#new', :as => :nuevoDeposito
  match '/archivo_proyectos/:id/new' => 'archivo_proyectos#new', :as => :nuevoArchivo
  match '/dropbox/:id/autenticar' => 'dropbox#autenticar',:as => :dropbox

app/models/plantilla.rb
VALID_NAME = /\w/
# = Modelo de plantilla
# Esta clase implementa el modelo en el patron MVC para la tabla de plantillas.
# Una plantilla es el diseño de un proceso utilizado en un proyecto.
# == Atributos
# * id : entero (llave primaria)
# * nombre : string
# * tipo_plantilla_id : entero
# * descripcion : string
# * imagen : file
#
# == Relaciones
# * tipo de plantilla: pertenencia
#
# == Restricciones
# * nombre: requerido, caracteres alfanumericos, longitud(140), unico
# * tipo_plantilla_id: requerido
class Plantilla < ActiveRecord::Base
  belongs_to :tipo_plantilla, :foreign_key => 'tipo_plantilla_id'
  attr_accessible :descripcion,:imagen, :nombre,:id,:tipo_plantilla, :tipo_plantilla_id
  self.primary_key = 'id'

  has_many :actividads, dependent: :destroy
  has_many :compuertus, dependent: :destroy
  has_many :eventos, dependent: :destroy
  has_many :ruta, dependent: :destroy

  has_many :my_js_trees, dependent: :destroy
  
  validates :tipo_plantilla, :presence => true
  validates :nombre, :presence => true , format: { with:VALID_NAME }, :length => { :maximum => 140 }

  has_attached_file :imagen, :url => "/images/plantillas/:id_:style.:extension",
                             #:path => ":rails_root/public/images/plantillas/:id_:style.:extension",
                             :path => ":rails_root/public/images/plantillas/:id_:style.img",
                             :default_url => "/images/default/missing_:style.png"
  attr_accessor :imagen_file_name
  attr_accessor :imagen_content_type
  attr_accessor :imagen_file_size
  attr_accessor :imagen_updated_at

  validates_attachment_size :imagen, :less_than => 1.megabytes
  validates_attachment_content_type :imagen, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/bmp']

end

app/controllers/plantillas_controller.rb
# = Controlador de Plantillas
# Esta clase implementa el controlador en el patron MVC para la tabla de plantillas.
# Una plantilla es el diseño de un proceso utilizado en un proyecto.

class PlantillasController < ApplicationController
  # GET /plantillas
  # GET /plantillas.json

  before_filter :authenticate_user!
   before_filter :define_path


  def define_path
    @public_path = File.join(Rails.root.to_s, 'public')
    @uploads_url = '/uploads'
    @upload_path = File.join(@public_path, @uploads_url)
    @current_url = params[:dir] || @uploads_url
    @current_path = File.join(@public_path, @current_url)+ '/*'
  end

  # ===  Accion Index
  # Lista todos las plantillas y las visualiza en una grilla
  def index
    @plantillas = Plantilla.all.sort_by(&:created_at).reverse

    @tipo_plantillas = TipoPlantilla.all.uniq
    @var=1

    @plantilla = Plantilla.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plantillas }
    end
  end

  # ===  Accion Show
  # Presenta la informacion del diseño de una plantilla de acuerdo al id enviado
  # GET /plantillas/1
  # GET /plantillas/1.json
  def show
    @plantilla = Plantilla.includes(:actividads).find(params[:id])

    @tipo_recursos=TipoRecurso.all.uniq

    #@actividad = Actividad.first;
    #@compuertu = Compuertu.new

    @actividads = Actividad.find_all_by_plantilla_id(@plantilla.id)
    @compuertas = Compuertu.find_all_by_plantilla_id(@plantilla.id)

   #  @my_js_tree_id= MyJsTree.last.id+1

   # get_statistics @actividads, @compuertas

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plantilla }
    end
  end

  # ===  Accion New
  # Presenta el formulario para la creacion de una plantilla
  # GET /plantillas/new
  # GET /plantillas/new.json
  def new
    @plantilla = Plantilla.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plantilla }
    end
  end

  def get_statistics actividads, compuertus

    @numactividades = actividads.count
    @numcompuertas = compuertus.count
    @duracionest = 0
    @costoest = 0
    @numrecursos = 0

    @workvstime = "[0, 0]"
    @costvstime = "[0, 0]"
    @workvsresu = "[0, 0]"


    @i = 0
    actividads.each do |act|
     @i = @i + 1

      @workvstime += ",[#{@i.to_s()}, #{act.duracion.to_s()}]"

     if act.duracion != nil then
       @duracionest += act.duracion
      end

      @acttiporecs = ActividadTiporecurso.find_all_by_actividad_id(act.id)

      @cost = 0
      @qty = 0
      @acttiporecs.each do |acttiporec|
        @cost = @cost + acttiporec.tipo_recurso.cost * acttiporec.cantidad
        @qty = @qty +  acttiporec.cantidad
      end
      @numrecursos += @qty
      @costoest += @cost
      @costvstime += ",[#{@i.to_s()}, #{@cost.to_s()}]"

    end
  end
  # ===  Accion edit
  # Presenta el formulario para la edicion de una plantilla
  # GET /plantillas/1/edit
  def edit
    @plantilla = Plantilla.find(params[:id])
  end

  # ===  Accion create
  # Crea una plantilla de acuerdo a los datos enviados en el formulario de creacion
  # POST /plantillas
  # POST /plantillas.json
  def create
    @plantilla = Plantilla.new(params[:plantilla])

    respond_to do |format|
      if @plantilla.save

        @nodo = MyJsTree.new(
          :parent_id => 0,
          :position => 0,
          :type => 'root',
          :title => @plantilla.nombre,
          :plantilla_id => Plantilla.last().id,
          :left => 0,
          :right => 0,
          :level => 0
          )

        if @nodo.save
          @nodo1 = MyJsTree.new(
          :parent_id => MyJsTree.last().id,
          :position => 0,
          :type => 'evento_inicio',
          :title => 'Inicio',
          :plantilla_id => Plantilla.last().id,
          :left => 0,
          :right => 0,
          :level => 0
          )

          if @nodo1.save
            @evento=Evento.new(
              :nombre=>'Inicio',
              :descripcion=> '',
              :tipo=> '1',
              :plantilla_id=> Plantilla.last().id,
              :my_js_tree_id=> MyJsTree.last().id
            )
            if @evento.save
              
              @tipo_plantillas = TipoPlantilla.all.uniq
              @tipo_recursos=TipoRecurso.all.uniq
              @actividads = Actividad.find_all_by_plantilla_id(@plantilla.id)
              @compuertas = Compuertu.find_all_by_plantilla_id(@plantilla.id)

              @message = t('datos_guardados')

              format.html { render action: "show" }
              format.json { render json: @plantilla, status: :created, location: @plantilla }
            end
           end

        end


        
      else
        format.html { render action: "new" }
        format.json { render json: @plantilla.errors, status: :unprocessable_entity }
      end
    end
  end

  # ===  Accion update
  # Actualiza una plantilla de acuerdo a los datos enviados en el formulario de edicion
  # PUT /plantillas/1
  # PUT /plantillas/1.json
  def update
    @plantilla = Plantilla.find(params[:id])

    respond_to do |format|
      if @plantilla.update_attributes(params[:plantilla])
        format.html { redirect_to @plantilla, notice: 'Plantilla was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plantilla.errors, status: :unprocessable_entity }
      end
    end
  end

  # ===  Accion destroy
  # Elimina una plantilla de acuerdo al id enviado
  # DELETE /plantillas/1
  # DELETE /plantillas/1.json
  def destroy
    @plantilla = Plantilla.find(params[:id])
    @plantilla.destroy

    respond_to do |format|
      format.html { redirect_to plantillas_url }
      format.json { head :no_content }
    end
  end

# ===  Accion existe
# Determina si existe un plantilla de acuerdo a un nombre
def existe
    @plantilla = Plantilla.find_by_nombre(params[:nombre])
    if(@plantilla)
      render :text => "true"
    else
      render :text => "false"
    end
  end

 protected

end

app/helpers/plantillas_helper.rb
module PlantillasHelper
end

app/views/plantillas/_actividad.html.erb
<iframe id="frame_actividad"  src="<%= request.protocol + request.host_with_port %>/blank.html" width="100%" height="1000px"  style="background: #F2F7FF " seamless></iframe>

app/views/plantillas/_visorproceso.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<script src="../assets/lib/raphael.js" type="text/javascript"></script>
<link rel="stylesheet" href="../assets/bpmnstyle.css" media="screen"></link>

<script src="http://ajax.googleapis.com/ajax/libs/dojo/1.7.2/dojo/dojo.js" data-dojo-config="async: true, parseOnLoad: true"></script>
<script>
  require({
    baseUrl: "./",
    packages: [
      { name: "dojo", location: "http://ajax.googleapis.com/ajax/libs/dojo/1.7.2/dojo" },
      { name: "dojox", location: "http://ajax.googleapis.com/ajax/libs/dojo/1.7.2/dojox" },
      { name: "dijit", location: "http://ajax.googleapis.com/ajax/libs/dojo/1.7.2/dijit" },
      { name: "bpmn", location: "/assets/bpmn", main: "core" }
    ]
  });
</script>
<script>
  require(["bpmn/core", "bpmn/editor", "dojo/domReady!"], function(bpmn, editor) {
    //editor.initDropZone("drop_zone");
    bpmn.parse("../assets/bpmn/test.bpmn", function() {
    bpmn.highlight(["UserTask_1"], {"color" : "red"});
    }, {
      diagramElement: "diagram",
      clickFn : function (elem) {
        alert(JSON.stringify(elem));
      }
    });
  });
</script>
<!--div id="drop_zone">Drop BPMN 2.0 XML here</div-->
<div id="wrapper">
  <div id="diagram" style="width: 100%; height: 400px"></div>
</div>

app/views/plantillas/index.html.erb
<%#
# = Vista de una grilla de plantillas
# Esta vista implementa la grilla de administración de plantillas
%>

<script type="text/javascript">
  var nuevoModalId = "#nuevoplantilla";
  var editarModalId = "#editarplantilla";
  var eliminarModalId = "#eliminarplantilla";
  var nameInputId = "plantilla_nombre";
  var validateNameUrl = "<%= request.protocol + request.host_with_port %>/plantillas/existe/nombre";
  var nuevoButtonId = "#new_plantilla";
  var editarButtonId = "#editarplantilla";
  var eliminarButtonId = "#eliminarplantilla";
</script>

<%= javascript_include_tag :'david-crud' %>

<script type="text/javascript">
  $(document).ready(function() {
    // Paginación - ordenamiento
    $("#plantillasTabla").tablesorter({ headers: { 0:{sorter: false}}})
    .tablesorterPager({container: $("#pager"),positionFixed: false, size: 30});

    // Callback de validacion de nombre repetido por ajax
    $.validator.addMethod("nombre_unico", validar_nombre_unico, "");

    // Validaciones de jquery
    $("#new_plantilla").validate({
      rules: {
        "plantilla[nombre]": {
          required: true,
          nombre_unico: true
        },
        "plantilla[tipo_plantilla_id]": {
          required: true
        }

      },
      messages: {
        "plantilla[nombre]": {
          required: "<%= t('mandatory') %>",
          nombre_unico: "<%= t('name_exist') %>"
        },
        "plantilla[tipo_plantilla_id]": {
          required: "<%= t('mandatory') %>"
        }
      }
    });
  });
</script>


<% @titulo = t('.title_pag') %>
<%= render "shared/encabezado_crud" %>


<!-- Menu y contenido-->
<div id="sgw_4_body" class="body sg_scroll_container sgw_entity_query_entity_query_page">

  <div class="contents" id="ext-gen77" >

    <%
    @filtroTexto = t('filtro')
    @verListaTexto = t('viewList')
    @verIconosTexto = t('viewSharp')

    @nuevoBotonId = "nuevo_plantilla"
    @nuevoBotonTexto = t('add')
    @nuevoPath = plantillas_path
    @nuevoModal = "nuevoplantilla"

    @editarBotonId = "editar_plantilla"
    @editarBotonTexto = t('edit')
    @editarPath = "#"
    @editarModal = "editarplantilla"

    @eliminarBotonId = "eliminar_plantilla"
    @eliminarBotonTexto = t('delete')
    @eliminarPath = "#"
    @eliminarModal = "eliminarplantilla"
    @eliminarConfirm = "Está seguro de querer eliminar la plantilla?"
  %>

    <%= render "shared/menu_crud" %>

    <!-- Formas de visualización en tabla o thumbnail,...-->
    <div id="layout_principal" class="sgw_new_grid sgw_entity_query_mode sg_scroll_container seltarget" style="left: 250px; top: 30px; ">
      <%
         if(@plantillas.count == 0)
      %>
          <div class="addnew">
            <%= t('no_created')%>.<br /><br />
            <a data-toggle="modal" role="button" class="btn" href="#nuevoplantilla">
              <%= image_tag "/images/add.png" %><br /><br />
              <%= t('add_new')%>.
            </a>
          </div>
      <%
         else
      %>
      <table id="plantillasTabla" class="table table-bordered table-striped tablesorter" >
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th><%= t('nombre')%> </th>
            <th><%= t('tipo_plantilla')%> </th>
            <th><%= t('descr')%> </th>
          </tr>
        </thead>
        <tbody>
          <% @plantillas.each do |plantilla| %>
            <tr id="<%= plantilla.id %>">
              <td style="vertical-align:middle"><input type="checkbox" /></td>
             <td>
               <% if FileTest.exist?(Dir.pwd + "/public/images/plantillas/" + plantilla.id.to_s() + "_original.img") %>
                   <%= image_tag "/images/plantillas/" + plantilla.id.to_s() + '_original.img', :size => "75x75" %>
               <% else %>
                   <%= image_tag "/images/noimage.jpg", :size => "75x75" %>
               <% end %>
             </td>
              <td  style="vertical-align:middle">
                <%= link_to plantilla.nombre, plantilla_path(plantilla) %>
              </td>
              <td style="vertical-align:middle"> <%= plantilla.tipo_plantilla.nombre %></td>
              <td style="vertical-align:middle"> <%= plantilla.descripcion %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
   <% end %>
    </div>

    <%= render "shared/filtro_crud" %>

    <%
    @pagTexto = @plantillas.count.to_s() + " " + t('listade')
    @porPagTexto = t('pag')
  %>

    <%= render "shared/footer_crud" %>
  </div>

</div>

<!-- Formularios de edicion -->
<% content_for :modal do %>
  <div id="nuevoplantilla" class="modal hide fade " role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3><%= t('add')%> <%= t('plantilla')%></h3>
    </div>

    <div class="modal-body">
      <div class="row-fluid">
        <%= form_for(@plantilla, :html=> {:multipart=>true}) do |f| %>

        <fieldset>
            <!-- Datos del proyecto
             ================================================== -->
            <div id="rol" >

              <div class="field">
                <%= f.label :nombre,  "*" + t('nombre')%><br />
                <%= f.text_field :nombre, :maxlength => 250 %>
              </div>
              <div class="field">
                <%= f.label :tipo_plantilla,  "*" + t('tipo_plantilla') %><br />
                <%= f.select :tipo_plantilla_id, TipoPlantilla.all.map{|p| [p.nombre, p.id]} %>
              </div>
              <div class="field">
                <%= f.label :descripcion, t('descr') %><br />
                <%= f.text_area :descripcion, :size => "30x10", :maxlength => 250 %>
              </div>
              <div class="field">
                <%= f.label :descripcion, t('imagen')%><br />
                <%= f.file_field :imagen %>
              </div>
            </div>
          </fieldset>

        </div>
      </div>
      <div class="modal-footer">
        <div class="actions"  align=right >

          <input id="crear_plantilla" class="btn primary"  name="commit" type="submit" value="<%= t('btnCrear')%>" />
          <button class="btn" data-dismiss="modal" aria-hidden="true"><%= t('btnCancelar')%></button>
        </div>
      </div>
    <% end %>

  </div>

<%end%>